AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation which creates the resources for the aws pyspark for glue 
### 
# Parameters for the cloudformation template
Parameters:
  S3PySparkBucketName:
    Type: String
    Description: Bucket name for the aws
  PreFixForGlueNotebookRoleAndPolicy:
    Type: String
    Description: Prefix for glue policy and role
Resources:
  S3BucketForData:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref S3PySparkBucketName
      Tags:
      - Key: identifier
        Value: pySparktutorial

  ###
  # Create Role for Glue Notebook and interactive sessions NB this allows access to all glue resources and S3
  GlueNotebookRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role for Glue Notebook PySpark. 
      MaxSessionDuration: 43200
      Policies:
        - PolicyName: !Sub ${PreFixForGlueNotebookRoleAndPolicy}Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "glue:*"
                  - "s3:*"
                  - "ec2:DescribeVpcEndpoints"
                  - "ec2:DescribeRouteTables"
                  - "ec2:CreateNetworkInterface"
                  - "ec2:DeleteNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcAttribute"
                  - "iam:ListRolePolicies"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "cloudwatch:PutMetricData"
                  - "ec2:CreateTags"
                  - "ec2:DeleteTags"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource: 
                  - "arn:aws:s3:::{S3PySparkBucketName}/*"
                  - "arn:aws:s3:::{S3PySparkBucketName}/"
              - Effect: Allow
                Action: 
                - "iam:GetRole"
                - "iam:PassRole"
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/${PreFixForGlueNotebookRoleAndPolicy}Role
      RoleName: !Sub ${PreFixForGlueNotebookRoleAndPolicy}Role